import Head from 'next/head'
import { useEffect } from 'react'
import {
  SectionTitle,
} from '../components/shared-styled'
 
export default function Blogs() {

    return (
      <div>
        <Head>t
          <title>Illini Blockchain</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <SectionTitle>Blogs</SectionTitle>
        
      </div>
    )
  }