import Head from 'next/head'
import {
  SectionTitle
} from '../components/shared-styled'

export default function ContactUs() {
    return (
      <div>
        <Head>
          <title>Illini Blockchain</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <SectionTitle>Contact Us</SectionTitle>       
  
      </div>
    )
  }