import Head from 'next/head'
import {
  NewsletterBanner,
  IlliniBlockchainMainComponent,
  PillarCard,
  StyledTitle,
  WhatDoWeDoComponent
} from "../components/home";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Illini Blockchain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <IlliniBlockchainMainComponent />

      <NewsletterBanner />

      <StyledTitle>What do we do?</StyledTitle>
      <WhatDoWeDoComponent>           
        <PillarCard
          title={'Education'}
          description={'Through a collection of medium articles, twitter posts,\
          notion pages, and educational blockchain events Illini Blockchain\
          educates people of all skill levels.'}
          pillar={'education'}
        />
        <PillarCard
          title={'Community'}
          description={'Through a collection of medium articles, twitter posts,\
          notion pages, and educational blockchain events Illini Blockchain\
          educates people of all skill levels.'}
          pillar={'community'}
        />
        <PillarCard
          title={'Projects'}
          description={'Through a collection of medium articles, twitter posts,\
          notion pages, and educational blockchain events Illini Blockchain\
          educates people of all skill levels.'}
          pillar={'projects'}
        />
      </WhatDoWeDoComponent>
      
    </div>
  )
}
