import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import styled from "styled-components"
import EducationCard from "../components/EducationCard"
import CommunityCard from "../components/CommunityCard"
import ProjectsCard from "../components/ProjectsCard"
import NewsletterBanner from "../components/NewsletterBanner"



const StyledHeader = styled.h1`
height: 138px;
background: #202020;
color: #ffffff; 
display: flex;
justify-content: left;
align-items: start;
`

const StyledTitle = styled.h2`
height: 138px;
background: #202020;
color: #ffffff; 
display: flex;
justify-content: center;
align-items: flex;
`

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Illini Blockchain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledHeader>Welcome to the home of Illini Blockchain</StyledHeader>
      <NewsletterBanner />
      <div>      
        <StyledTitle>What do we do?</StyledTitle> 
      </div>
      <EducationCard />
      <CommunityCard />
      <ProjectsCard />
    </div>
  )
}
