import Head from 'next/head'
import Navbar from '../components/nav'
import styles from '../styles/Home.module.css'
import styled from 'styled-components';
import {
  StyledHeader
} from '../components/shared-styled'

export default function Projects() {
    return (
      <div className={styles.container}>
        <Head>t
          <title>Illini Blockchain</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <StyledHeader>Projects</StyledHeader>       

      </div>
    )
  }