import Head from 'next/head'
import {
  SectionTitle,
  Container
} from '../components/shared-styled'

export default function Projects() {
    return (
      <Container>
        <Head>t
          <title>Illini Blockchain</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <SectionTitle>Projects</SectionTitle>       

      </Container>
    )
  }