import Head from 'next/head'
import {
  SectionTitle,
  Container
} from '../components/shared-styled'
import {
  Project,
  ProjectsContainer
} from '../components/projects'

export default function Projects() {
    return (
      <>
        <Head>t
          <title>Illini Blockchain</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <SectionTitle>Projects</SectionTitle>

        <ProjectsContainer>

          <Project
            title={'NFT Mint'}
            imageSrc={'/illiniBlockchainNFT.svg'}
            imageAlt={'Illini NFT Mint Image'}
            stack={['Next.js', 'ethers.js']}
            githubUrl={'https://github.com/IlliniBlockchain/nft-mint'}
            websiteUrl={'https://illini-mint.vercel.app/'}
            description={'We built this simple web app to make it easy for anyone interested in blockchain to get involved and start playing with the technology. The site will walk you through the process of opening an Ethereum wallet and minting your very own Illini Blockchain NFT. We\'ve done our best to design this so that you don\'t need to know much about blockchain to jump right in.'}
          />

        </ProjectsContainer>

      </>
    )
  }